<?php

namespace Database\Seeders;

use App\Models\CurrentProject;
use Illuminate\Database\Seeder;

class CurrentProjectSeeder extends Seeder
{
    public function run(): void
    {
        // Clear existing projects
        CurrentProject::truncate();

        $projects = [
            // === PROPOSED PROJECTS SM - MID - LARGE (A, B, C) ===
            [
                'name_en' => 'Fuel Storage Plant',
                'name_es' => 'Planta de Almacenamiento de Combustible',
                'description_en' => 'Strategic fuel storage facility designed to ensure energy security and supply chain resilience for national operations.',
                'description_es' => 'Planta estratégica de almacenamiento de combustible diseñada para garantizar la seguridad energética y la resiliencia de la cadena de suministro para operaciones nacionales.',
                'location_en' => 'Bolivia',
                'location_es' => 'Bolivia',
                'status' => 'active',
                'category' => CurrentProject::CATEGORY_PROPOSED_SM_MID_LARGE,
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'name_en' => 'Achumani Diplomatic Center',
                'name_es' => 'Centro Diplomático de Achumani',
                'description_en' => 'A premier diplomatic center in Achumani serving as a hub for international relations, strategic meetings, and diplomatic coordination.',
                'description_es' => 'Un centro diplomático de primer nivel en Achumani que sirve como centro para relaciones internacionales, reuniones estratégicas y coordinación diplomática.',
                'location_en' => 'Achumani, Bolivia',
                'location_es' => 'Achumani, Bolivia',
                'status' => 'active',
                'category' => CurrentProject::CATEGORY_PROPOSED_SM_MID_LARGE,
                'sort_order' => 2,
                'is_active' => true,
            ],
            [
                'name_en' => 'CIZZE Project',
                'name_es' => 'Proyecto CIZZE',
                'description_en' => 'Specialized project focused on advanced infrastructure development and institutional strengthening.',
                'description_es' => 'Proyecto especializado enfocado en el desarrollo de infraestructura avanzada y fortalecimiento institucional.',
                'location_en' => 'Bolivia',
                'location_es' => 'Bolivia',
                'status' => 'active',
                'category' => CurrentProject::CATEGORY_PROPOSED_SM_MID_LARGE,
                'sort_order' => 3,
                'is_active' => true,
            ],
            // === CLASSIFIED (D-O) ===
            [
                'name_en' => 'Stock/Micro Loans Project',
                'name_es' => 'Proyecto Stock/Micro Loans',
                'description_en' => 'Financial inclusion initiative providing stock investments and micro-lending solutions to empower local communities and small businesses.',
                'description_es' => 'Iniciativa de inclusión financiera que proporciona inversiones en acciones y soluciones de microcrédito para empoderar a las comunidades locales y pequeñas empresas.',
                'location_en' => 'Bolivia',
                'location_es' => 'Bolivia',
                'status' => 'active',
                'category' => CurrentProject::CATEGORY_CLASSIFIED,
                'sort_order' => 4,
                'is_active' => true,
            ],
            [
                'name_en' => 'Coca - Coffee Project',
                'name_es' => 'Proyecto Coca - Coffee',
                'description_en' => 'Agricultural transformation program aimed at transitioning coca cultivation to sustainable coffee production, supporting farmers and economic development.',
                'description_es' => 'Programa de transformación agrícola orientado a la transición del cultivo de coca hacia la producción sostenible de café, apoyando a los agricultores y el desarrollo económico.',
                'location_en' => 'Bolivia',
                'location_es' => 'Bolivia',
                'status' => 'active',
                'category' => CurrentProject::CATEGORY_CLASSIFIED,
                'sort_order' => 5,
                'is_active' => true,
            ],
            [
                'name_en' => 'Armed Forces REVAMP Project',
                'name_es' => 'Proyecto REVAMP de las Fuerzas Armadas',
                'description_en' => 'Comprehensive modernization and restructuring program for the Armed Forces, including training, equipment upgrades, and operational readiness enhancement.',
                'description_es' => 'Programa integral de modernización y reestructuración de las Fuerzas Armadas, incluyendo capacitación, actualización de equipos y mejora de la preparación operativa.',
                'location_en' => 'Bolivia',
                'location_es' => 'Bolivia',
                'status' => 'active',
                'category' => CurrentProject::CATEGORY_CLASSIFIED,
                'sort_order' => 6,
                'is_active' => true,
            ],
            [
                'name_en' => 'National Police REVAMP Project',
                'name_es' => 'Proyecto REVAMP de las Policía Nacional',
                'description_en' => 'Comprehensive modernization and restructuring program for the National Police, focused on institutional reform, training, and operational capability improvement.',
                'description_es' => 'Programa integral de modernización y reestructuración de la Policía Nacional, enfocado en reforma institucional, capacitación y mejora de capacidad operativa.',
                'location_en' => 'Bolivia',
                'location_es' => 'Bolivia',
                'status' => 'active',
                'category' => CurrentProject::CATEGORY_CLASSIFIED,
                'sort_order' => 7,
                'is_active' => true,
            ],
            [
                'name_en' => 'Law and Order Project',
                'name_es' => 'Proyecto Ley y Orden',
                'description_en' => 'Rule of law strengthening initiative designed to enhance justice systems, legal frameworks, and public security infrastructure.',
                'description_es' => 'Iniciativa de fortalecimiento del estado de derecho diseñada para mejorar los sistemas de justicia, marcos legales e infraestructura de seguridad pública.',
                'location_en' => 'Bolivia',
                'location_es' => 'Bolivia',
                'status' => 'active',
                'category' => CurrentProject::CATEGORY_CLASSIFIED,
                'sort_order' => 8,
                'is_active' => true,
            ],
            [
                'name_en' => 'Penitentiary System Project',
                'name_es' => 'Proyecto del Régimen Penitenciario',
                'description_en' => '1) Ultra Max Prison Center. 2) Med-High Prison Center. 3) Labor Camp A, B, C. 4) Agronomic and Bovine Production Farm.',
                'description_es' => '1) Centro de Prision Ultra Max. 2) Centro Prision Med - High. 3) Campo de Trabajo A,B,C. 4) Quinta Producción Agrónoma y Bovina.',
                'location_en' => 'Bolivia',
                'location_es' => 'Bolivia',
                'status' => 'active',
                'category' => CurrentProject::CATEGORY_CLASSIFIED,
                'sort_order' => 9,
                'is_active' => true,
            ],
            [
                'name_en' => 'Education First / ROTC Program',
                'name_es' => 'Programa Educación Primero/ROTC',
                'description_en' => 'Educational development program integrating academic excellence with ROTC-style leadership training for youth empowerment and national service.',
                'description_es' => 'Programa de desarrollo educativo que integra la excelencia académica con formación de liderazgo tipo ROTC para el empoderamiento juvenil y servicio nacional.',
                'location_en' => 'Bolivia',
                'location_es' => 'Bolivia',
                'status' => 'active',
                'category' => CurrentProject::CATEGORY_CLASSIFIED,
                'sort_order' => 10,
                'is_active' => true,
            ],
            [
                'name_en' => 'Oil, Gas and Energy Program',
                'name_es' => 'Programa Petroleo, Gas y Energía',
                'description_en' => 'Strategic energy sector development program encompassing petroleum, gas extraction, and energy infrastructure modernization.',
                'description_es' => 'Programa estratégico de desarrollo del sector energético que abarca petróleo, extracción de gas y modernización de infraestructura energética.',
                'location_en' => 'Bolivia',
                'location_es' => 'Bolivia',
                'status' => 'active',
                'category' => CurrentProject::CATEGORY_CLASSIFIED,
                'sort_order' => 11,
                'is_active' => true,
            ],
            [
                'name_en' => 'New Bolivia Construction Program',
                'name_es' => 'Programa de Construcción Nueva Bolivia',
                'description_en' => 'Large-scale national construction program focused on building modern infrastructure, housing, and public facilities across Bolivia.',
                'description_es' => 'Programa nacional de construcción a gran escala enfocado en construir infraestructura moderna, viviendas e instalaciones públicas en toda Bolivia.',
                'location_en' => 'Bolivia',
                'location_es' => 'Bolivia',
                'status' => 'active',
                'category' => CurrentProject::CATEGORY_CLASSIFIED,
                'sort_order' => 12,
                'is_active' => true,
            ],
            [
                'name_en' => 'Cement Plant 1-2',
                'name_es' => 'Planta de Cemento 1- 2',
                'description_en' => 'Industrial cement production facility supporting national construction and infrastructure development projects.',
                'description_es' => 'Planta industrial de producción de cemento que respalda proyectos nacionales de construcción y desarrollo de infraestructura.',
                'location_en' => 'Bolivia',
                'location_es' => 'Bolivia',
                'status' => 'active',
                'category' => CurrentProject::CATEGORY_CLASSIFIED,
                'sort_order' => 13,
                'is_active' => true,
            ],
            [
                'name_en' => 'Vad Vad Interlocking Block Program',
                'name_es' => 'Programa Vad Vad Interlocking Block',
                'description_en' => 'Innovative construction materials program producing interlocking blocks for sustainable and cost-effective building solutions.',
                'description_es' => 'Programa innovador de materiales de construcción que produce bloques entrelazados para soluciones de construcción sostenibles y rentables.',
                'location_en' => 'Bolivia',
                'location_es' => 'Bolivia',
                'status' => 'active',
                'category' => CurrentProject::CATEGORY_CLASSIFIED,
                'sort_order' => 14,
                'is_active' => true,
            ],
            [
                'name_en' => 'The Dream Center Bolivia Project',
                'name_es' => 'Proyecto The Dream Center Bolivia',
                'description_en' => 'Community development center providing social services, education, and empowerment programs for underserved populations.',
                'description_es' => 'Centro de desarrollo comunitario que proporciona servicios sociales, educación y programas de empoderamiento para poblaciones desatendidas.',
                'location_en' => 'Bolivia',
                'location_es' => 'Bolivia',
                'status' => 'active',
                'category' => CurrentProject::CATEGORY_CLASSIFIED,
                'sort_order' => 15,
                'is_active' => true,
            ],
            // === PROPOSED MEGA PROJECTS ===
            [
                'name_en' => 'Project Un Nuevo Horizonte (Airport & Bullet Train Patacamaya) *RUSFER*',
                'name_es' => 'Project Un Nuevo Horizonte (Aeropuerto y Tren Bala Patacamaya) *RUSFER*',
                'description_en' => 'Mega infrastructure project featuring a state-of-the-art international airport and high-speed bullet train system in Patacamaya, developed in partnership with RUSFER.',
                'description_es' => 'Megaproyecto de infraestructura que incluye un aeropuerto internacional de última generación y un sistema de tren bala de alta velocidad en Patacamaya, desarrollado en asociación con RUSFER.',
                'location_en' => 'Patacamaya, Bolivia',
                'location_es' => 'Patacamaya, Bolivia',
                'status' => 'upcoming',
                'category' => CurrentProject::CATEGORY_PROPOSED_MEGA,
                'sort_order' => 16,
                'is_active' => true,
            ],
            [
                'name_en' => 'Project COLPABOL (Bolivian Atlantic Port Logistics Corridor) *RUSFER*',
                'name_es' => 'Project COLPABOL (Corredor Logístico Portuario Atrantico Boliviano) *RUSFER*',
                'description_en' => '1. Railway large-scale cargo transport (Mutun - Puerto Bush). 2. Paved road regional connectivity (Pto. Suarez-Mutun-Pto. Bush). 3. Three Specialized River Terminals: Terminal for grains, Terminal for fuels, Terminal for iron ore. 4. Shipyard construction at Pto. Tamarinero in Canala Tamengo (Pto. Quijarro). 5. Reconstruction of Pto. Tamarinero in Canal Tamengo (Pto. Quijarro). 6. Latest generation Airport (CAT III-A, 4E OACO).',
                'description_es' => '1. Línea Férrea Transporte carga de gran escala (Mutun - Puerto Bush). 2. Carretera asfaltada conectividad regional (Pto. Suarez-Mutun-Pto. Bush). 3. Tres Terminales Fluviales Especializadas: Terminal para granos, Terminal para combustibles, Terminal para mineral de hierro. 4. Astillero fabricación del Pto. Tamarinero en Canala Tamengo (Pto. Quijarro). 5. Reconstrucción del Pto. Tamarinero en Canal Tamengo (Pto. Quijarro). 6. Aeropuerto última generación (CAT III-A, 4E OACO).',
                'location_en' => 'Eastern Bolivia',
                'location_es' => 'Oriente Boliviano',
                'status' => 'upcoming',
                'category' => CurrentProject::CATEGORY_PROPOSED_MEGA,
                'sort_order' => 17,
                'is_active' => true,
            ],
            [
                'name_en' => 'Oil & Gas Project',
                'name_es' => 'Project Petróleo & Gas',
                'description_en' => 'Strategic petroleum and natural gas exploration, extraction, and processing mega project for national energy independence and export capability.',
                'description_es' => 'Megaproyecto estratégico de exploración, extracción y procesamiento de petróleo y gas natural para la independencia energética nacional y capacidad de exportación.',
                'location_en' => 'Bolivia',
                'location_es' => 'Bolivia',
                'status' => 'upcoming',
                'category' => CurrentProject::CATEGORY_PROPOSED_MEGA,
                'sort_order' => 18,
                'is_active' => true,
            ],
        ];

        foreach ($projects as $project) {
            CurrentProject::create($project);
        }
    }
}
